swagger: "2.0"
info:
  title: sentinel-luna
  description: "Sentinel UI for QoE Degradations"
  version: 0.0.1
host: "luna-dot-ql-sen-stag.appspot.com"
schemes:
  - https
security:
  - api_key: []
securityDefinitions:
  api_key:
    type: apiKey
    name: key
    in: query
paths:
  /:
    get:
      description: "Render Luna UI"
      operationId: "getLunaUI"
      responses:
        200:
          description: "OK"
