# Copyright 2017, Google, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
# If this is the first Google App Engine Service you are deploying,
# change 'modelserve' to 'default', since the first service must be
# named 'default'.
service: hermione
runtime: python27
runtime_config:
  python_version: 2
threadsafe: false
entrypoint: gunicorn -b :$PORT hermione:app

api_version: 1

manual_scaling:
  instances: 1


#endpoints_api_service:
#  name: hermione-dot-ql-sen-stag.appspot.com
#  config_id: 2018-02-06r0

handlers:
  - url: /doc
    static_files: doc/index.html
    upload: doc/index\.html
  - url: /doc/(.*)
    static_files: docs/\1
    upload: doc/.
  - url: /openapi\.yaml
    static_files: openapi.yaml
    upload: openapi\.yaml
  - url: /(.*)
    script: hermione.app

env_variables:
    TXP_BUCKET: ql-sen-stag
    TXP_FOLDER: texp/incidents
    TXP_BULK: texp/bulk

libraries:
  - name: ssl
    version: latest
  - name: numpy
    version: "1.6.1"

